name: Deploy to Hostinger via SSH

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.HOSTINGER_KEY }}

      - name: Add Hostinger to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.HOSTINGER_PORT }} ${{ secrets.HOSTINGER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via rsync
        run: |
          rsync -avz --delete \
            -e "ssh -p ${{ secrets.HOSTINGER_PORT }}" \
            dist/ \
            ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:public_html/

      - name: Debug
        run: |
         ssh -p ${{ secrets.HOSTINGER_PORT }} \
           ${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }} \
           'head -n 20 public_html/index.html'
